ProManage/ProManage/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('account.urls')),
]

ProManage/account/urls.py
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
  path('signup/', views.signup, name='signup'),
  path('login/', views.login, name='login')
]

ProManage/core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
]

ProManage/account/models.py
from typing import Any
import uuid

from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, UserManager, Group, Permission
from django.db import models


class CustomUserManager(UserManager):
    def _create_user(self, name, email, password, **extra_fields):
        if not email:
            raise ValueError("You did not provide a valid email address")

        email = self.normalize_email(email)
        user = self.model(email=email, name=name, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)

        return user

    def create_user(self, name=None, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(name, email, password, **extra_fields)

    def create_superuser(self, name=None, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        return self._create_user(name, email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    email = models.EmailField(unique=True)
    name = models.CharField(max_length=255, blank=True, null=True)

    is_active = models.BooleanField(default=True)
    is_superuser = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)

    date_joined = models.DateTimeField(auto_now_add=True)
    last_login = models.DateTimeField(blank=True, null=True)

    groups = models.ManyToManyField(
        Group,
        related_name='custom_user_set',  # Adding related_name to avoid clashes
        blank=True
    )
    user_permissions = models.ManyToManyField(
        Permission,
        related_name='custom_user_set',  # Adding related_name to avoid clashes
        blank=True
    )

    objects = CustomUserManager()

    USERNAME_FIELD = 'email'
    EMAIL_FIELD = 'email'
    REQUIRED_FIELDS = ['name']

ProManage/core/models.py
from django.db import models

# Create your models here.

ProManage/account/views.py
from django.contrib.auth import authenticate, login as auth_login
from django.shortcuts import render, redirect

from .models import User

def login(request):
  if request.method == 'POST':
    email = request.POST.get('email','')
    password = request.POST.get('password', '')
    print('request')

    if email and password:
      user = authenticate(request, email=email, password=password)
      print('User :', user)
      if user is not None:
        auth_login(request, user)
        print('User', user)

        print(request.user)
        print(request.user.is_authenticated)

        return redirect('/')
  return render(request, 'account/login.html')

def signup(request):
  if request.method == 'POST':
    name = request.POST.get('name', '')
    email = request.POST.get('email', '')
    password = request.POST.get('password', '')
    password2 = request.POST.get('password2', '')

    if name and email and password and password2:
      user = User.objects.create_user(name, email, password)
      print('User created : ', user)

      return redirect('/login/')
    else:
      print('Something went wrong')
  

  else:
    print('Just show the form !')
  
  return render(request, 'account/signup.html')

# Create your views here.

ProManage/core/views.py
from django.shortcuts import render

def index(request):
  return render(request, 'core/index.html')

def about(request):
  return render(request, 'core/about.html')
# Create your views here.

ProManage/core/templates/core/about.html
{% extends 'core/base.html' %}

{% block content %}
<h1 class="text-3xl">About</h1>
    <div class="mt-6 py-6 px-8">
      <p>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Impedit, ipsum. Nostrum velit commodi saepe ducimus ullam id reiciendis enim inventore nisi, impedit eligendi debitis! Odio impedit quo ut sequi explicabo.
      </p>

      <p>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Impedit, ipsum. Nostrum velit commodi saepe ducimus ullam id reiciendis enim inventore nisi, impedit eligendi debitis! Odio impedit quo ut sequi explicabo.
      </p>
    </div>

{% endblock %}

ProManage/core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="https://cdn.tailwindcss.com"></script>
  <title>About</title>
</head>

<body>
  <nav class="py-6 px-8 flex items-center justify-between bg-slate-800">
    <h1 class="text-2xl text-white"> <a href="{% url 'core:index' %}">ProManage</a></h1>

    <div>
      <a href="{% url 'core:about' %}" class="text-white">About</a>
      <a href="{% url 'account:login' %}" class="py-4 px-8 bg-slate-600 text-white">Log in</a>
      <a href="{% url 'account:signup' %}" class="py-4 px-8 bg-sky-600 text-white">Sign up</a>
    </div>
  </nav>

  <main class="py-6 px-8">
    {% block content %}
    {% endblock %}
  </main>

  <footer class="py-8 px-8 bg-slate-900 text-center">
    <p class="text-white">Copyright (c) 2024 - Manan Bhardwaj</p>
  </footer>
</body>

</html>

ProManage/core/templates/core/index.html
{% extends 'core/base.html' %}

{% block content %}
<header class="py-12 text-center bg-slate-200">
  <h1 class="text-3xl">Welcome to ProManage</h1>
</header>

{% endblock %}